{% set name = "pygslodeiv2" %}
{% set version = "0.9.6" %}
{% set sha256 = "4e0a55c22d91d4ace303c74c3c0adf4618b4bb1d8c414e19f8f85b9ab2012024" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  skip: true  # [osx and py<36]
  features:
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - numpy
    - gsl
    - cython
  run:
    - python
    - gsl

test:
  imports:
    - {{ name }}
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs {{ name }}

about:
  home: https://github.com/bjodah/{{ name }}
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Python binding for odeiv2 interface from GNU Scientific Library (GSL)
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
